version: 2.1
workflows:
  test_app:
    jobs:
      - test
jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install
          command: npm ci
      - run:
          name: Test
          command: npm run coverage
      - run:
          name: Coverage Upload
          command: npx tubs upload ./coverage
      - run:
          name: Badge Purge
          command: npx camo-purge --repository https://github.com/jchancehud/wrapped-deposit
